---
title: "Hourly forecasting in ED and Ambulance services"
author: "Bahman Rostami-Tabar"
date: "27/05/2020"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(patchwork)
library(fable)
library(feasts)
library(tsibble)
library(tidyverse)
```

## Hourly time series

```{r hourly,fig.align='center',out.width="75%"}
h2_hourly <- readr::read_rds("../data/h2_hourly.rds")
h2_hourly <- h2_hourly %>% filter(arrival_1h >="2015-01-01 00:00:00"&arrival_1h <"2019-01-01 00:00:00")
  subseriesplot <- h2_hourly %>% as_tibble() %>% mutate(day=factor(yday(arrival_1h)),year=factor(year(arrival_1h)),hour=hour(arrival_1h)) %>% 
    select(-arrival_1h)
time <-  format( seq.POSIXt(as.POSIXct(Sys.Date()), as.POSIXct(Sys.Date()+1), by = "1 hour"),
                 "%H:%M", tz="GMT")
time <- time[-length(time)]
p1 <- ggplot(data=subseriesplot,mapping = aes(x=hour ,y=n_attendance, colour=day))+
    geom_line(aes(group=interaction(day,year)))+
    geom_point()+
    theme_bw()+
    theme(legend.position = "")+
    labs(y="Number of visits in ED", x="Hour of day")+
      scale_x_continuous(breaks=0:23, labels = time)+
  theme(axis.text.x = element_text(angle = 90))
  p1+theme(plot.title = element_text(size = 10))
```

## 2 shifts

```{r 2shift, fig.align='center',fig.width=15, fig.height=7}

ed_2shoft <- h2_hourly %>% as_tibble() %>% mutate(Date=date(arrival_1h),Hour=hour(arrival_1h)) %>% mutate(shift=if_else(Hour <= 12,"shift_1", "shift_2")) %>% 
  group_by(Date,Hour,shift) %>% summarise(n_attendance=sum(n_attendance))
  
  ed_2shoft %>%
  ggplot(mapping = aes(x=n_attendance))+
  geom_histogram(aes(y = stat(density)),binwidth = 1,color = 'black')+
    geom_density(color="blue")+
    scale_y_continuous(labels = scales::percent_format())+
  facet_wrap(~shift)+
    theme_bw()+
    labs(x="Number of visits in ED", y="Percentage")
```

## 3 shifts

```{r 3shift, fig.align='center',fig.width=15, fig.height=7}
h2_hourly %>% as_tibble() %>% mutate(Date=date(arrival_1h),Hour=hour(arrival_1h)) %>% mutate(shift=
case_when(Hour < 9 ~"shift_1", 8 < Hour & Hour < 17 ~ "shift_2", TRUE ~ "shift_3")) %>% 
group_by(Date,shift) %>% summarise(n_attendance=sum(n_attendance)) %>% 
ggplot(mapping = aes(x=n_attendance))+
geom_histogram(mapping=aes(y=stat(density)), binwidth = 1,fill="white",color = 'black')+
  geom_density(color="blue")+
scale_y_continuous(labels = scales::percent_format())+
facet_wrap(~shift, scales = "free")+
  theme_bw()+
  labs(x="Number of visits in ED", y="Percentage")

```

## 4 shifts

```{r 4shift, fig.align='center',fig.width=9, fig.height=9}
h2_hourly %>% as_tibble() %>% mutate(Date=date(arrival_1h),Hour=hour(arrival_1h)) %>% mutate(shift=
  case_when(Hour < 6 ~"shift_1", 6 <= Hour & Hour < 12 ~ "shift_2",12 <= Hour & Hour < 18 ~ "shift_3", TRUE ~ "shift_4")) %>% 
  group_by(Date,shift) %>% summarise(n_attendance=sum(n_attendance)) %>% 
  ggplot(mapping = aes(x=n_attendance))+
geom_histogram(mapping=aes(y=stat(density)), binwidth = 1,fill="white",color = 'black')+
  geom_density(color="blue")+
scale_y_continuous(labels = scales::percent_format())+
facet_wrap(~shift, scales = "free")+
  theme_bw()+
  labs(x="Number of visits in ED", y="Percentage")
```


## 24 hours

```{r 24shift, fig.align='center',fig.width=10, fig.height=20}
h2_hourly %>% as_tibble() %>% mutate(Date=date(arrival_1h),Hour=hour(arrival_1h)) %>% 
  select(-arrival_1h) %>% ggplot(mapping=aes(x=n_attendance))+ 
geom_histogram(mapping=aes(y=stat(density)), binwidth = 1,fill="white",color = 'black')+
  geom_density(color="blue")+
scale_y_continuous(labels = scales::percent_format())+
facet_wrap(~Hour, scales = "free", ncol = 3)+
  theme_bw()+
  labs(x="Number of visits in ED", y="Percentage")
```
